// Copy the documents the script package generates into the site.
//
//   node scripts/sync-docs.js           write docs/reference/generated/*.md
//   node scripts/sync-docs.js --check   exit 1 if any copy is stale
//
// EVENTS.md and PAGE_DISPATCH.md are regenerated by the package's build, so
// the site copies them rather than keeping a second version to drift. Each
// copy gets Docusaurus frontmatter, a banner naming its source, and the few
// rewrites plain Markdown needs to survive MDX: HTML comments go, `<br>`
// closes itself, relative links point at GitHub, braces and placeholder tags
// are escaped. Fenced code and inline code are left exactly as written.
//
// Runs before `start` and `build` (see package.json); the output directory is
// git-ignored.

'use strict';

const fs = require('fs');
const path = require('path');

const siteDir = path.resolve(__dirname, '..');
const packageDir = path.resolve(siteDir, '..', 'app.gap.Tsum');
const outDir = path.join(siteDir, 'docs', 'reference', 'generated');
const githubBlob = 'https://github.com/game-automation-platform/game-automation-scripts/blob/main/app.gap.Tsum/';

const documents = [
  {
    from: 'EVENTS.md',
    to: 'events.md',
    title: 'Emitted events',
    label: 'Emitted events',
    regen: 'npm run events:docs',
    description: 'Every event the script broadcasts to outside tooling, and what each carries.',
  },
  {
    from: 'PAGE_DISPATCH.md',
    to: 'page-dispatch.md',
    title: 'Page dispatch',
    label: 'Page dispatch',
    regen: 'npm run pages:docs',
    description: 'What happens on every recognised screen, in the order it happens.',
  },
  {
    from: 'BACKLOG.md',
    to: 'backlog.md',
    title: 'Backlog',
    label: 'Backlog',
    regen: null,
    description: 'Known bugs and wanted features, straight from the repository.',
  },
];

// Tags that may stay as HTML; anything else in angle brackets is a placeholder.
const htmlTags = new Set(['br', 'sub', 'sup', 'b', 'i', 'em', 'strong', 'kbd', 'code']);

function escapeProse(text) {
  // Split on inline code so the rewrites never touch a code span.
  return text.split(/(`[^`]*`)/).map((part, i) => {
    if (i % 2 === 1) return part;
    return part
      .replace(/<br>/g, '<br />')
      .replace(/[{}]/g, (c) => '\\' + c)
      .replace(/<(\/?)([A-Za-z][\w-]*)([^>]*)>/g, (m, slash, tag) =>
        htmlTags.has(tag.toLowerCase()) ? m : m.replace('<', '&lt;').replace(/>$/, '&gt;'))
      .replace(/\]\(([^)\s]+)\)/g, (m, target) => {
        if (/^(https?:|#|mailto:)/.test(target)) return m;
        const [file, anchor] = target.split('#');
        return '](' + githubBlob + file + (anchor ? '#' + anchor : '') + ')';
      });
  }).join('');
}

function transform(markdown, doc) {
  const lines = markdown.replace(/<!--[\s\S]*?-->\n?/g, '').split('\n');
  const out = [];
  let inFence = false;
  let titleDropped = false;
  for (const line of lines) {
    if (/^\s*```/.test(line)) {
      inFence = !inFence;
      out.push(line);
      continue;
    }
    if (inFence) { out.push(line); continue; }
    if (!titleDropped && /^# /.test(line)) { titleDropped = true; continue; }
    out.push(escapeProse(line));
  }
  const body = out.join('\n').replace(/^\n+/, '');
  const regen = doc.regen
    ? ` Regenerate it there with \`${doc.regen}\`; edits here are lost at the next sync.`
    : ' Edit it there; edits here are lost at the next sync.';
  return [
    '---',
    `id: ${path.basename(doc.to, '.md')}`,
    `title: ${doc.title}`,
    `sidebar_label: ${doc.label}`,
    `description: ${doc.description}`,
    'custom_edit_url: null',
    '---',
    '',
    ':::info Copied from the repository',
    `This page is \`app.gap.Tsum/${doc.from}\`, copied in by the site's sync step.${regen}`,
    ':::',
    '',
    body,
  ].join('\n');
}

function main() {
  const check = process.argv.includes('--check');
  fs.mkdirSync(outDir, { recursive: true });
  let stale = 0;
  for (const doc of documents) {
    const source = fs.readFileSync(path.join(packageDir, doc.from), 'utf8');
    const target = path.join(outDir, doc.to);
    const wanted = transform(source, doc);
    const current = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : null;
    if (current === wanted) continue;
    stale++;
    if (check) {
      console.error(`stale: docs/reference/generated/${doc.to} (from ${doc.from})`);
    } else {
      fs.writeFileSync(target, wanted);
      console.log(`wrote docs/reference/generated/${doc.to}`);
    }
  }
  if (check && stale) process.exit(1);
  if (!check && !stale) console.log('generated docs are up to date');
}

main();
