// English log sentences -- the reference table.
//
// `LogCatalogue` is `typeof` this object, so this file is the list: a
// translation may only answer keys that appear here, and `logStringsFor` fills
// its gaps from here. See `src/logs.ts` for the registry and the rules.

var LogsEn = {
  [Log.Run.Start]: '[TsumTsum] Start',
  [Log.Run.StartBusy]: '[TsumTsum] The previous run has not stopped yet; not starting a second one',
  [Log.Run.Stop]: '[TsumTsum] Stop',
  [Log.Run.StopSlow]: '[TsumTsum] The task loop has not handed back yet; leaving it to finish',
  [Log.Task.LoopStopped]: 'TaskController Stop',
  [Log.Board.Recognized]: 'Recognized Tsums',
  [Log.Board.RecognitionStart]: 'Start Tsums recognition',
  [Log.Board.RecognitionTime]: 'Tsums recognised',
  [Log.Board.PathStart]: 'Start path calculation',
  [Log.Board.PathDone]: 'Calculated path',
  [Log.Board.LinkReach]: 'Link reach',
  [Log.Board.DeadScan]: 'The chain was drawn but its tsums are still standing',
  [Log.Board.Stalled]: 'The board has stopped taking chains; fanning it to shake the tsums loose',
  [Log.Bubble.Cleared]: 'Clear bubbles',
  [Log.Bubble.Generated]: 'Bubble generated',
  [Log.Skill.Use]: 'Use skill',
  [Log.Skill.ReadyAgain]: 'Skill full again off its own burst; sweeping bubbles and going round again',
  [Log.Skill.TiaraNoDream]: '[Tiara] No thought bubble appeared',
  [Log.Skill.TiaraDimDream]: '[Tiara] Thought bubble was gone before it could be read',
  [Log.Skill.TiaraBusy]: '[Tiara] Board still moving, firing anyway',
  [Log.Skill.TiaraDream]: '[Tiara] Bubble shows',
  [Log.Skill.TiaraPicked]: '[Tiara] Tapped',
  [Log.Skill.TiaraUnsure]: '[Tiara] No present matched confidently, stopping',
  [Log.Skill.FormalBeastModeStart]: '[Formal Beast] Twin gauge is up; keeping the two halves level',
  [Log.Skill.FormalBeastModeEnd]: '[Formal Beast] Twin gauge is gone',
  [Log.Skill.ElsaDone]: '[Coronation Elsa] Freeze window closed',
  [Log.Skill.GastonDone]: '[Gaston] Gaston window closed',
  [Log.Skill.GastonPass]: '[Gaston] Chain drawn',
  [Log.Skill.RapunzelDone]: '[Rapunzel+] Mixed-colour chain drawn',
  [Log.Skill.LorcanaAuroraDone]: '[Lorcana Aurora] Bubble chain drawn',
  [Log.Skill.LorcanaAuroraNoChain]: '[Lorcana Aurora] No bubbles to chain -- the skill went to waste',
  [Log.Skill.LorcanaAuroraStayed]: '[Lorcana Aurora] Chain drawn but the bubbles stayed -- the game did not take it',
  [Log.Skill.LorcanaAuroraSwept]: '[Lorcana Aurora] Bubbles popped where they stood',
  [Log.Play.GameStart]: 'Game Start',
  [Log.Play.GamingFast]: 'Playing',
  [Log.Play.GameOver]: 'Game Over',
  [Log.Play.ConfirmingGameOver]: 'Screen not recognized, confirming game over (skill animation?)',
  [Log.Play.CheckBonusItems]: 'Check bonus items',
  [Log.Play.RoundDelayStarted]: 'Waiting before the next round',
  [Log.Play.RoundDelayOver]: 'The wait is over; starting the next round',
  [Log.Play.RoundDelaySkipped]: 'The wait was cut short; starting the next round',
  [Log.Play.RoundTimeUp]: 'The round hit the Max Round Duration cap',
  [Log.Play.RoundCoastGaveUp]: 'The round never ended on its own; handing the task back',
  [Log.Tsums.Identified]: 'MyTsum identified',
  [Log.Tsums.Unidentified]: 'Could not tell which tsum is selected; the round will be recorded without one',
  [Log.Tsums.Unreadable]: 'Could not read the pre-round tsum icon',
  [Log.Tsums.NoLibrary]: 'The tsum library could not be loaded, so rounds are recorded without a tsum',
  [Log.Tsums.StaleTemplate]: 'The tsum library does not match this release and is being ignored',
  [Log.Tsums.NoBoardColors]: 'The tsum library carries no board colours for this release, so "Link MyTsum first" falls back to sampling the skill button',
  [Log.Lorcana.Transformed]: '[Lorcana] Transformed',
  [Log.Lorcana.Untransformed]: '[Lorcana] The gauge ring round the skill button is back -- not transformed after all',
  [Log.Fever.Start]: '[Fever] Fever time',
  [Log.Fever.End]: '[Fever] Fever over',
  [Log.Screen.Detect]: 'Detecting screen (top and bottom)',
  [Log.Screen.CalculateSize]: 'Calculating screen size',
  [Log.Screen.Offset]: 'Screen offset and size',
  [Log.App.Start]: 'Start TsumTsum app',
  [Log.Page.Current]: 'Current page',
  [Log.Page.Friends]: 'Friends page',
  [Log.Page.Tsums]: 'Tsum collection page',
  [Log.Gifts.ReceiveAll]: 'Receive all gifts',
  [Log.Gifts.ReceiveOneByOne]: 'Receive gift one by one',
  [Log.Gifts.ReceiveAgain]: 'Receive gift again',
  [Log.Gifts.AllReceived]: 'All gifts received',
  [Log.Gifts.Completed]: 'Receiving gifts completed',
  [Log.Gifts.CheckUnreceived]: 'Check unreceived gift',
  [Log.Gifts.ReceiveOneMedalsOnly]: 'Nothing but medals left in the mailbox',
  [Log.Hearts.ReadRecords]: 'Reading records',
  [Log.Hearts.SaveRecords]: 'Saving records',
  [Log.Hearts.SendStart]: 'Start sending hearts',
  [Log.Hearts.SendDone]: 'Finished sending hearts',
  [Log.Hearts.Screenful]: 'Hearts sent from this part of the ranking',
  [Log.Hearts.ListEnd]: 'Reached the end of the ranking',
  [Log.Hearts.ZeroScore]: 'Reached the friends with no score',
  [Log.Hearts.TimeUp]: 'Time\'s up',
  [Log.Report.Saved]: 'Saved a report of what is on screen',
  [Log.Report.Failed]: 'Could not save the report',
  [Log.Walk.Start]: 'Walkthrough recording: drive the game yourself',
  [Log.Walk.Page]: 'Screen recorded',
  [Log.Walk.Tap]: 'Tap recorded',
  [Log.Walk.Done]: 'Walkthrough recorded',
  [Log.Unlock.NowQueued]: 'Raising level caps at the next turn of the task loop',
  [Log.Unlock.NowRefused]: 'Not raising level caps now',
  [Log.Unlock.NowWaiting]: 'A round is in progress; raising level caps once it is over',
  [Log.Unlock.NowYielded]: 'Stepping aside for the level-cap sweep',
  [Log.Unlock.Start]: 'Looking for Tsums at their level cap',
  [Log.Unlock.Raised]: 'Raised a Tsum\'s level cap',
  [Log.Unlock.NextPage]: 'All eight capped; on to the next page of the collection',
  [Log.Unlock.SortFailed]: 'Could not change the collection\'s order',
  [Log.Unlock.SortRestored]: 'Put the collection back in its previous order',
  [Log.Unlock.RaiseNotConfirmed]: 'The level cap did not go up -- out of coins?',
  [Log.Unlock.Retrying]: 'That raise did not take; taking the collection page again',
  [Log.Unlock.End]: 'Finished raising Tsum level caps',
  [Log.Box.NowQueued]: 'Buying boxes at the next turn of the task loop',
  [Log.Box.NowRefused]: 'Not buying boxes now',
  [Log.Box.NowWaiting]: 'A round is in progress; buying boxes once it is over',
  [Log.Box.Start]: 'Off to the Tsum Tsum Store to buy boxes',
  [Log.Box.StoreLoading]: 'The store did not finish loading its boxes',
  [Log.Box.NotOffered]: 'The store is not selling that box today',
  [Log.Box.TabNotTaken]: 'The store would not open that box',
  [Log.Box.Buying]: 'Buying a box',
  [Log.Box.Bought]: 'Bought a box',
  [Log.Box.SoldOut]: 'That box is sold out',
  [Log.Box.NoCoins]: 'Not enough Coins -- cancelled, and no Rubies spent',
  [Log.Box.DialogMissing]: 'The purchase confirmation did not open',
  [Log.Box.Retrying]: 'That purchase did not take; taking the store page again',
  [Log.Box.RevealsStuck]: 'The boxes would not finish opening',
  [Log.Box.PurchaseLimit]: 'Reached the purchase limit for this sweep',
  [Log.Box.End]: 'Finished buying boxes'
}

logRegisterStrings(Locale.English, LogsEn);
