// Traditional Chinese (Taiwan) log sentences.
//
// `LogCataloguePartial`, so it may omit a key: `logStringsFor` fills the gap
// from `src/logsEn.ts`, which is what lets a new event ship a sentence before it
// has been translated. `npm run i18n:check` lists what is still missing.

var LogsZhTw: LogCataloguePartial = {
  [Log.Run.Start]: '[TsumTsum] 啟動',
  [Log.Run.StartBusy]: '[TsumTsum] 上一次執行尚未停止，不重複啟動',
  [Log.Run.Stop]: '[TsumTsum] 停止',
  [Log.Run.StopSlow]: '[TsumTsum] 任務迴圈尚未交還，等待其自行結束',
  [Log.Task.LoopStopped]: 'TaskController 停止',
  [Log.Board.Recognized]: '成功辨識 Tsums',
  [Log.Board.RecognitionStart]: '開始辨識 Tsums',
  [Log.Board.RecognitionTime]: 'Tsums 辨識完成',
  [Log.Board.PathStart]: '開始計算路徑',
  [Log.Board.PathDone]: '成功計算路徑',
  [Log.Board.LinkReach]: '連線距離',
  [Log.Board.DeadScan]: '已畫出連線，但連線上的 Tsum 仍在原位',
  [Log.Board.Stalled]: '盤面已無法連線，改用風扇搧散 Tsum',
  [Log.Bubble.Cleared]: '清除泡泡',
  [Log.Bubble.Generated]: '產生泡泡',
  [Log.Skill.Use]: '使用技能',
  [Log.Skill.ReadyAgain]: '技能因自身爆發再次集滿，清除泡泡後再次發動',
  [Log.Skill.TiaraNoDream]: '[皇冠米妮] 沒有出現想像泡泡',
  [Log.Skill.TiaraDimDream]: '[皇冠米妮] 想像泡泡在讀取前已消失',
  [Log.Skill.TiaraBusy]: '[皇冠米妮] 畫面仍在變動，仍然發動',
  [Log.Skill.TiaraDream]: '[皇冠米妮] 泡泡顯示',
  [Log.Skill.TiaraPicked]: '[皇冠米妮] 點擊',
  [Log.Skill.TiaraUnsure]: '[皇冠米妮] 沒有禮物符合，停止',
  [Log.Skill.FormalBeastModeStart]: '[禮服野獸] 雙量表出現，維持兩側平衡',
  [Log.Skill.FormalBeastModeEnd]: '[禮服野獸] 雙量表結束',
  [Log.Skill.ElsaDone]: '[加冕日艾莎] 冰凍時間結束',
  [Log.Skill.GastonDone]: '[加斯頓] 加斯頓時間結束',
  [Log.Skill.GastonPass]: '[加斯頓] 已連出連線',
  [Log.Skill.RapunzelDone]: '[樂佩+] 已連出混色連線',
  [Log.Skill.LorcanaAuroraDone]: '[Lorcana 奧蘿拉] 已連出泡泡連線',
  [Log.Skill.LorcanaAuroraNoChain]: '[Lorcana 奧蘿拉] 沒有泡泡可連，技能浪費了',
  [Log.Skill.LorcanaAuroraStayed]: '[Lorcana 奧蘿拉] 已畫出連線但泡泡還在，遊戲沒有接受這次拖曳',
  [Log.Skill.LorcanaAuroraSwept]: '[Lorcana 奧蘿拉] 已就地點破泡泡',
  [Log.Play.GameStart]: '遊戲開始',
  [Log.Play.GamingFast]: '遊戲中',
  [Log.Play.GameOver]: '遊戲結束',
  [Log.Play.ConfirmingGameOver]: '無法辨識畫面，確認遊戲是否結束（技能動畫中？）',
  [Log.Play.CheckBonusItems]: '檢查道具',
  [Log.Play.RoundDelayStarted]: '下一局前先休息',
  [Log.Play.RoundDelayOver]: '休息結束，開始下一局',
  [Log.Play.RoundDelaySkipped]: '休息已略過，開始下一局',
  [Log.Play.RoundTimeUp]: '本局已達單局時間上限',
  [Log.Play.RoundCoastGaveUp]: '本局始終沒有結束，先把工作交回排程',
  [Log.Tsums.Identified]: '使用中的 Tsum',
  [Log.Tsums.Unidentified]: '無法辨識選取的 Tsum，本局將不記錄 Tsum',
  [Log.Tsums.Unreadable]: '無法讀取開始畫面的 Tsum 圖示',
  [Log.Tsums.NoLibrary]: '無法載入 Tsum 樣板，記錄將不含 Tsum',
  [Log.Tsums.StaleTemplate]: 'Tsum 樣板與此版本不符，已略過',
  [Log.Tsums.NoBoardColors]: 'Tsum 樣板不含此版本的盤面顏色，「優先連結我的 Tsum」改為讀取技能按鈕',
  [Log.Lorcana.Transformed]: '[Lorcana] 已變身',
  [Log.Lorcana.Untransformed]: '[Lorcana] 技能按鈕旁的變身環又出現了，其實尚未變身',
  [Log.Fever.Start]: '[Fever] Fever 時間',
  [Log.Fever.End]: '[Fever] Fever 結束',
  [Log.Screen.Detect]: '偵測畫面 (頂部與底部)',
  [Log.Screen.CalculateSize]: '計算螢幕大小',
  [Log.Screen.Offset]: '畫面位移與大小',
  [Log.App.Start]: '啟動 TsumTsum 應用程式',
  [Log.Page.Current]: '目前頁面',
  [Log.Page.Friends]: '朋友頁面',
  [Log.Page.Tsums]: 'Tsum收集页面',
  [Log.Gifts.ReceiveAll]: '接收所有禮物',
  [Log.Gifts.ReceiveOneByOne]: '一個一個接收禮物',
  [Log.Gifts.ReceiveAgain]: '再嘗試接收禮物一次',
  [Log.Gifts.AllReceived]: '已接收所有禮物',
  [Log.Gifts.Completed]: '完成接收禮物',
  [Log.Gifts.CheckUnreceived]: '檢查未接收的禮物',
  [Log.Gifts.ReceiveOneMedalsOnly]: '信箱裡只剩獎章了',
  [Log.Hearts.ReadRecords]: '讀取紀錄',
  [Log.Hearts.SaveRecords]: '儲存紀錄',
  [Log.Hearts.SendStart]: '開始送愛心',
  [Log.Hearts.SendDone]: '送愛心完成',
  [Log.Hearts.Screenful]: '這一頁送出的愛心',
  [Log.Hearts.ListEnd]: '已到排行榜底部',
  [Log.Hearts.ZeroScore]: '已到 0 分的好友',
  [Log.Hearts.TimeUp]: '送心時間結束',
  [Log.Report.Saved]: '已儲存目前畫面的問題回報',
  [Log.Report.Failed]: '無法儲存問題回報',
  [Log.Walk.Start]: '導覽紀錄中，請自行操作遊戲',
  [Log.Walk.Page]: '已紀錄畫面',
  [Log.Walk.Tap]: '已紀錄點擊',
  [Log.Walk.Done]: '導覽紀錄完成',
  [Log.Unlock.NowQueued]: '任務迴圈下一輪即提升等級上限',
  [Log.Unlock.NowRefused]: '現在無法提升等級上限',
  [Log.Unlock.NowWaiting]: '這一局還在進行中，結束後再提升等級上限',
  [Log.Unlock.NowYielded]: '先讓給提升等級上限的作業',
  [Log.Unlock.Start]: '尋找已達等級上限的 Tsum',
  [Log.Unlock.Raised]: '已提升 Tsum 的等級上限',
  [Log.Unlock.NextPage]: '八隻都已達上限，前往收藏的下一頁',
  [Log.Unlock.SortFailed]: '無法變更收藏的排序',
  [Log.Unlock.SortRestored]: '已將收藏恢復為原本的排序',
  [Log.Unlock.RaiseNotConfirmed]: '等級上限沒有提升 — 金幣不足？',
  [Log.Unlock.Retrying]: '這次提升沒有成功，重新讀取收藏頁面',
  [Log.Unlock.End]: '提升 Tsum 等級上限完成'
}

logRegisterStrings(Locale.Taiwan, LogsZhTw);
